name: APR-Projekt.1.19.3
version: '${project.version}'
main: at.eugene.aprprojekt.Main
api-version: 1.19
commands:
  timer:
    permission: aprprojekt.command.timer
  deaths:
    permission: aprprojekt.command.deaths
